export const AWARDS = [
  {
    title: 'Ganador Convocatoria de Estímulos',
    titleEn: 'Grant Program Winner',
    org: 'Banda Sinfónica Juvenil de Colombia — Ministerio de Cultura',
    orgEn: 'Youth Symphonic Band of Colombia — Ministry of Culture',
    year: '2013',
  },
  {
    title: 'Ganador Convocatoria de Estímulos',
    titleEn: 'Grant Program Winner',
    org: 'Banda Sinfónica Juvenil de Colombia — Ministerio de Cultura',
    orgEn: 'Youth Symphonic Band of Colombia — Ministry of Culture',
    year: '2015',
  },
  {
    title: 'Ganador Concurso Internacional de Trombón — Pasto',
    titleEn: 'Winner, International Trombone Competition — Pasto',
    org: 'Festival Internacional de Trombón',
    orgEn: 'International Trombone Festival',
    year: '2018',
  },
  {
    title: 'Ganador Jóvenes Solistas',
    titleEn: 'Winner, Young Soloists',
    org: 'Orquesta Sinfónica de Caldas — Universidad de Caldas',
    orgEn: 'Caldas Symphony Orchestra — Universidad de Caldas',
    year: '2018',
  },
  {
    title: 'Ganador Concurso Universitario de Trombón SIT',
    titleEn: 'Winner, SIT University Trombone Competition',
    org: 'Universidad de Antioquia',
    orgEn: 'Universidad de Antioquia',
    year: '2019',
  },
  {
    title: 'Ganador "Jóvenes Solistas" y "Gaspar Licciardone"',
    titleEn: 'Winner, "Young Soloists" and "Gaspar Licciardone"',
    org: 'Trombonanza — Argentina',
    orgEn: 'Trombonanza — Argentina',
    year: '2019',
  },
  {
    title: 'Becario Festival de Música de Cartagena',
    titleEn: 'Scholarship Recipient, Cartagena Music Festival',
    org: 'Fundación Salvi',
    orgEn: 'Fundación Salvi',
    year: '2019',
  },
  {
    title: 'Ganador con Mención de Honor, Concurso Jóvenes Solistas',
    titleEn: 'Winner with Honorable Mention, Young Soloists Competition',
    org: 'Banda Departamental del Valle',
    orgEn: 'Valle Departmental Band',
    year: '2022',
  },
  {
    title: 'Ganador Jóvenes Intérpretes',
    titleEn: 'Winner, Young Performers Series',
    org: 'Banco de la República',
    orgEn: 'Banco de la República',
    year: '2022/25',
  },
  {
    title: 'Ganador Concurso Interno de Solistas',
    titleEn: 'Winner, Internal Soloist Competition',
    org: 'Orquesta Sinfónica Nacional de Colombia',
    orgEn: 'National Symphony Orchestra of Colombia',
    year: '2022',
  },
];